# -*- coding: utf-8 -*-
"""Scheduled wrappers for monthly air quality consultation supplements."""

from __future__ import annotations

from datetime import datetime, timedelta
from typing import Optional, Tuple

import structlog

from app.fetchers.base.fetcher_interface import DataFetcher
from app.fetchers.consultation.monthly_district_pollutant_ranking import (
    generate_district_pollutant_ranking,
)
from app.fetchers.consultation.monthly_meteorology_support import (
    generate_meteorology_support,
)
from app.fetchers.consultation.monthly_pollution_events_components import (
    generate_pollution_events_components,
)
from app.fetchers.consultation.monthly_station_high_values import (
    generate_station_high_values,
)

logger = structlog.get_logger()


def get_previous_month(reference_time: Optional[datetime] = None) -> Tuple[int, int]:
    """Return the complete month that should be generated by monthly fetchers."""
    today = reference_time or datetime.now()
    last_month = today.replace(day=1) - timedelta(days=1)
    return last_month.year, last_month.month


class MonthlyDistrictPollutantRankingFetcher(DataFetcher):
    """Generate monthly district pollutant ranking supplement data."""

    def __init__(self):
        super().__init__(
            name="monthly_district_pollutant_ranking_fetcher",
            description="月度区县污染物排名补充数据 - 每月4号7点30分生成上个月完整数据",
            schedule="30 7 4 * *",
            version="1.0.0",
        )

    async def fetch_and_store(self):
        year, month = get_previous_month()
        output_path = generate_district_pollutant_ranking(year, month)
        logger.info(
            "monthly_district_pollutant_ranking_generated",
            year=year,
            month=month,
            output_path=str(output_path) if output_path else None,
        )


class MonthlyStationHighValuesFetcher(DataFetcher):
    """Generate monthly high-value station supplement data."""

    def __init__(self):
        super().__init__(
            name="monthly_station_high_values_fetcher",
            description="月度高值站点补充数据 - 每月4号7点40分生成上个月完整数据",
            schedule="40 7 4 * *",
            version="1.0.0",
        )

    async def fetch_and_store(self):
        year, month = get_previous_month()
        output_path = generate_station_high_values(year, month)
        logger.info(
            "monthly_station_high_values_generated",
            year=year,
            month=month,
            output_path=str(output_path) if output_path else None,
        )


class MonthlyPollutionEventsComponentsFetcher(DataFetcher):
    """Generate monthly pollution events and component supplement data."""

    def __init__(self):
        super().__init__(
            name="monthly_pollution_events_components_fetcher",
            description="月度污染时段及组分补充数据 - 每月4号7点50分生成上个月完整数据",
            schedule="50 7 4 * *",
            version="1.0.0",
        )

    async def fetch_and_store(self):
        year, month = get_previous_month()
        output_path = generate_pollution_events_components(year, month)
        logger.info(
            "monthly_pollution_events_components_generated",
            year=year,
            month=month,
            output_path=str(output_path) if output_path else None,
        )


class MonthlyMeteorologySupportFetcher(DataFetcher):
    """Generate monthly CMA meteorology support data."""

    def __init__(self):
        super().__init__(
            name="monthly_meteorology_support_fetcher",
            description="月度气象支撑数据 - 每月1号12点30分抓取上个月完整窗口的气温距平图、降水距平百分率图和6项同比统计",
            schedule="30 12 1 * *",
            version="1.0.0",
        )

    async def fetch_and_store(self):
        year, month = get_previous_month()
        output_path = generate_meteorology_support(year, month)
        logger.info(
            "monthly_meteorology_support_generated",
            year=year,
            month=month,
            output_path=str(output_path) if output_path else None,
        )
