import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import assert from 'node:assert/strict'

const rightPanelSource = readFileSync(resolve('frontend/src/components/reactAnalysis/RightPanelContainer.vue'), 'utf8')
const mainLayoutSource = readFileSync(resolve('frontend/src/components/reactAnalysis/MainLayout.vue'), 'utf8')
const panelManagementSource = readFileSync(resolve('frontend/src/composables/reactAnalysis/usePanelManagement.js'), 'utf8')
const rightPanelStateSource = readFileSync(resolve('frontend/src/composables/reactAnalysis/useRightPanelState.js'), 'utf8')
const sessionApiSource = readFileSync(resolve('frontend/src/api/session.js'), 'utf8')
const sessionManagementSource = readFileSync(resolve('frontend/src/composables/reactAnalysis/useSessionManagement.js'), 'utf8')
const boardPanelPath = resolve('frontend/src/components/board/DrawioBoardPanel.vue')

assert.equal(existsSync(boardPanelPath), true, 'DrawioBoardPanel.vue should exist')

const boardPanelSource = readFileSync(boardPanelPath, 'utf8')
const inputBoxSource = readFileSync(resolve('frontend/src/components/InputBox.vue'), 'utf8')

assert.match(rightPanelSource, /DrawioBoardPanel/, 'RightPanelContainer should import and render DrawioBoardPanel')
assert.match(rightPanelSource, /activeTab === 'board'/, 'RightPanelContainer should render board tab content')
assert.match(rightPanelSource, />\s*画板\s*</, 'RightPanelContainer should expose a 画板 tab label')
assert.match(rightPanelSource, /showBoardTab/, 'RightPanelContainer should gate the board tab')
assert.doesNotMatch(rightPanelSource, /assistantMode\s*===\s*['"]chart['"]/, 'RightPanelContainer should not hide restored board tabs outside chart mode')
assert.match(rightPanelSource, /hasBoardXml/, 'RightPanelContainer should expose a board tab when restored board XML exists')
assert.match(rightPanelSource, /board-xml-change/, 'RightPanelContainer should emit board XML changes')
assert.match(rightPanelSource, /board-selection-change/, 'RightPanelContainer should emit board selection changes')
assert.match(rightPanelSource, /board-snapshot-confirm/, 'RightPanelContainer should emit confirmed board snapshots')

assert.match(mainLayoutSource, /board-panel-visible/, 'MainLayout should pass board panel visibility')
assert.match(mainLayoutSource, /board-xml-change/, 'MainLayout should forward board XML changes')
assert.match(mainLayoutSource, /board-selection-change/, 'MainLayout should forward board selection changes')
assert.match(mainLayoutSource, /board-snapshot-confirm/, 'MainLayout should forward confirmed board snapshots')

assert.match(panelManagementSource, /boardPanelVisible/, 'usePanelManagement should expose boardPanelVisible')
assert.match(rightPanelStateSource, /boardPanelVisible/, 'useRightPanelState should expose boardPanelVisible')
assert.match(sessionApiSource, /getSessionDrawioBoard/, 'session API should expose draw.io board lazy loading')
assert.match(sessionApiSource, /\/drawio-board/, 'session API should call the draw.io board lazy endpoint')
assert.match(sessionManagementSource, /getSessionDrawioBoard/, 'session restore should lazy-load draw.io board state')
assert.match(sessionManagementSource, /has_lazy_drawio_board/, 'session restore should track lazy draw.io board availability')

assert.match(boardPanelSource, /embed\.diagrams\.net/, 'DrawioBoardPanel should embed diagrams.net')
assert.match(boardPanelSource, /saveAndExit=0/, 'DrawioBoardPanel should hide draw.io Save and Exit controls')
assert.match(boardPanelSource, /noSaveBtn=1/, 'DrawioBoardPanel should hide draw.io Save controls')
assert.match(boardPanelSource, /noExitBtn=1/, 'DrawioBoardPanel should hide draw.io Exit controls')
assert.match(boardPanelSource, /postMessage/, 'DrawioBoardPanel should communicate with draw.io through postMessage')
assert.match(boardPanelSource, /xml-change/, 'DrawioBoardPanel should emit XML changes')
assert.match(boardPanelSource, /selection-change/, 'DrawioBoardPanel should emit selection changes')
assert.match(boardPanelSource, /AI编辑/, 'DrawioBoardPanel should surface an AI edit indicator when cells are selected')
assert.match(boardPanelSource, /selectedCellsForAiEdit/, 'DrawioBoardPanel should keep local selected cells for the AI edit indicator')
assert.match(boardPanelSource, /ai-edit-indicator/, 'DrawioBoardPanel should render a dedicated AI edit indicator overlay')
assert.match(boardPanelSource, /pointer-events:\s*none/, 'AI edit indicator overlay should not block draw.io canvas interaction')
assert.match(boardPanelSource, /selectionProbeInterval/, 'DrawioBoardPanel should actively poll draw.io selection while the iframe is focused')
assert.match(boardPanelSource, /selection:\s*true/, 'DrawioBoardPanel should request selected cells through draw.io export selection mode')
assert.match(boardPanelSource, /format:\s*['"]json['"]/, 'DrawioBoardPanel should request structural JSON for selection probing')
assert.match(boardPanelSource, /getDrawioSelectionPayloadFromExport/, 'DrawioBoardPanel should parse selected cells from draw.io JSON export responses')
assert.match(boardPanelSource, /重新加载/, 'DrawioBoardPanel should use a clear reload label')
assert.match(boardPanelSource, /对话附图/, 'DrawioBoardPanel should use a concise conversation attachment label')
assert.doesNotMatch(boardPanelSource, /snapshotPending/, 'DrawioBoardPanel should treat conversation attachment as a one-shot action')
assert.doesNotMatch(boardPanelSource, /class=["'][^"']*board-btn[^"']*active|:class=.*active/, 'DrawioBoardPanel should not show the conversation attachment button as selected')
assert.doesNotMatch(rightPanelSource, /snapshot-pending/, 'RightPanelContainer should not pass selected state to DrawioBoardPanel')
assert.match(boardPanelSource, /board-snapshot-confirm/, 'DrawioBoardPanel should emit confirmed PNG snapshots')
assert.match(boardPanelSource, /action:\s*['"]export['"]|postDrawio\(['"]export['"]/, 'DrawioBoardPanel should request PNG export from draw.io')
assert.match(boardPanelSource, /导出图片/, 'DrawioBoardPanel should expose a manual image export action')
assert.match(boardPanelSource, /downloadBoardImage/, 'DrawioBoardPanel should download exported board images')
assert.match(boardPanelSource, /\.png/, 'DrawioBoardPanel should support PNG image downloads')
assert.match(boardPanelSource, /\.drawio/, 'DrawioBoardPanel should support .drawio downloads')
assert.doesNotMatch(boardPanelSource, /board-btn primary/, 'DrawioBoardPanel toolbar buttons should use a consistent visual style')

const mainViewSource = readFileSync(resolve('frontend/src/views/ReactAnalysisView.vue'), 'utf8')
const refactoredViewSource = readFileSync(resolve('frontend/src/views/ReactAnalysisViewRefactored.vue'), 'utf8')
assert.match(mainViewSource, /board-snapshot-confirm/, 'ReactAnalysisView should receive confirmed board snapshots')
assert.match(refactoredViewSource, /board-snapshot-confirm/, 'ReactAnalysisViewRefactored should receive confirmed board snapshots')

assert.match(inputBoxSource, /pendingSnapshotAttachment/, 'InputBox should display pending draw.io board snapshots as attachments')
assert.match(inputBoxSource, /visibleAttachments/, 'InputBox should merge normal uploads with pending board snapshots for preview')
assert.match(inputBoxSource, /clearDrawioBoardSnapshotAttachment|setDrawioBoardSnapshotAttachment\(null/, 'InputBox should allow removing pending board snapshots')
