import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import assert from 'node:assert/strict'

const rightPanelSource = readFileSync(resolve('frontend/src/components/reactAnalysis/RightPanelContainer.vue'), 'utf8')
const mainLayoutSource = readFileSync(resolve('frontend/src/components/reactAnalysis/MainLayout.vue'), 'utf8')
const panelManagementSource = readFileSync(resolve('frontend/src/composables/reactAnalysis/usePanelManagement.js'), 'utf8')
const rightPanelStateSource = readFileSync(resolve('frontend/src/composables/reactAnalysis/useRightPanelState.js'), 'utf8')
const sessionApiSource = readFileSync(resolve('frontend/src/api/session.js'), 'utf8')
const sessionManagementSource = readFileSync(resolve('frontend/src/composables/reactAnalysis/useSessionManagement.js'), 'utf8')
const boardPanelPath = resolve('frontend/src/components/board/DrawioBoardPanel.vue')

assert.equal(existsSync(boardPanelPath), true, 'DrawioBoardPanel.vue should exist')

const boardPanelSource = readFileSync(boardPanelPath, 'utf8')
const inputBoxSource = readFileSync(resolve('frontend/src/components/InputBox.vue'), 'utf8')

assert.match(rightPanelSource, /DrawioBoardPanel/, 'RightPanelContainer should import and render DrawioBoardPanel')
assert.match(rightPanelSource, /activeTab === 'board'/, 'RightPanelContainer should render board tab content')
assert.match(rightPanelSource, />\s*画板\s*</, 'RightPanelContainer should expose a 画板 tab label')
assert.match(rightPanelSource, /showBoardTab/, 'RightPanelContainer should gate the board tab')
assert.doesNotMatch(rightPanelSource, /assistantMode\s*===\s*['"]chart['"]/, 'RightPanelContainer should not hide restored board tabs outside chart mode')
assert.match(rightPanelSource, /hasBoardXml/, 'RightPanelContainer should expose a board tab when restored board XML exists')
assert.match(rightPanelSource, /board-xml-change/, 'RightPanelContainer should emit board XML changes')
assert.match(rightPanelSource, /board-selection-change/, 'RightPanelContainer should emit board selection changes')
assert.match(rightPanelSource, /board-snapshot-confirm/, 'RightPanelContainer should emit confirmed board snapshots')

assert.match(mainLayoutSource, /board-panel-visible/, 'MainLayout should pass board panel visibility')
assert.match(mainLayoutSource, /board-xml-change/, 'MainLayout should forward board XML changes')
assert.match(mainLayoutSource, /board-selection-change/, 'MainLayout should forward board selection changes')
assert.match(mainLayoutSource, /board-snapshot-confirm/, 'MainLayout should forward confirmed board snapshots')

assert.match(panelManagementSource, /boardPanelVisible/, 'usePanelManagement should expose boardPanelVisible')
assert.match(rightPanelStateSource, /boardPanelVisible/, 'useRightPanelState should expose boardPanelVisible')
assert.match(sessionApiSource, /getSessionDrawioBoard/, 'session API should expose draw.io board lazy loading')
assert.match(sessionApiSource, /\/drawio-board/, 'session API should call the draw.io board lazy endpoint')
assert.match(sessionManagementSource, /getSessionDrawioBoard/, 'session restore should lazy-load draw.io board state')
assert.match(sessionManagementSource, /has_lazy_drawio_board/, 'session restore should track lazy draw.io board availability')

assert.match(boardPanelSource, /embed\.diagrams\.net/, 'DrawioBoardPanel should embed diagrams.net')
assert.match(boardPanelSource, /saveAndExit=0/, 'DrawioBoardPanel should hide draw.io Save and Exit controls')
assert.match(boardPanelSource, /noSaveBtn=1/, 'DrawioBoardPanel should hide draw.io Save controls')
assert.match(boardPanelSource, /noExitBtn=1/, 'DrawioBoardPanel should hide draw.io Exit controls')
assert.match(boardPanelSource, /postMessage/, 'DrawioBoardPanel should communicate with draw.io through postMessage')
assert.match(boardPanelSource, /xml-change/, 'DrawioBoardPanel should emit XML changes')
assert.match(boardPanelSource, /selection-change/, 'DrawioBoardPanel should emit selection changes')
assert.doesNotMatch(boardPanelSource, /AI编辑/, 'DrawioBoardPanel should not overlay AI edit status on top of draw.io controls')
assert.doesNotMatch(boardPanelSource, /selectedCellsForAiEdit/, 'DrawioBoardPanel should not keep separate overlay-only selected cell state')
assert.doesNotMatch(boardPanelSource, /ai-edit-indicator/, 'DrawioBoardPanel should not render a dedicated AI edit indicator overlay')
assert.match(boardPanelSource, /selectionProbeInterval/, 'DrawioBoardPanel should actively poll draw.io selection while the iframe is focused')
assert.match(boardPanelSource, /selection:\s*true/, 'DrawioBoardPanel should request selected cells through draw.io export selection mode')
assert.match(boardPanelSource, /format:\s*['"]json['"]/, 'DrawioBoardPanel should request structural JSON for selection probing')
assert.match(boardPanelSource, /getDrawioSelectionPayloadFromExport/, 'DrawioBoardPanel should parse selected cells from draw.io JSON export responses')
assert.match(boardPanelSource, /xmlSyncPending/, 'DrawioBoardPanel should actively sync XML while the iframe is focused')
assert.match(boardPanelSource, /format:\s*['"]xml['"]/, 'DrawioBoardPanel should request XML exports for manual edit history')
assert.match(boardPanelSource, /getExportXml/, 'DrawioBoardPanel should parse XML export responses')
assert.match(boardPanelSource, /xml\s*===\s*latestXml\.value/, 'DrawioBoardPanel should not reload draw.io after editor-originated XML updates')
assert.match(boardPanelSource, /重新加载/, 'DrawioBoardPanel should use a clear reload label')
assert.match(boardPanelSource, /版本文件/, 'DrawioBoardPanel should expose draw.io version files using the file history pattern')
assert.match(boardPanelSource, /versionFiles/, 'DrawioBoardPanel should receive draw.io version files')
assert.match(boardPanelSource, /currentVersionId/, 'DrawioBoardPanel should mark the active draw.io version file')
assert.match(boardPanelSource, /version-restore/, 'DrawioBoardPanel should emit version restore events')
assert.doesNotMatch(boardPanelSource, />\s*撤销\s*</, 'DrawioBoardPanel should rely on draw.io built-in undo controls')
assert.doesNotMatch(boardPanelSource, />\s*重做\s*</, 'DrawioBoardPanel should rely on draw.io built-in redo controls')
assert.doesNotMatch(boardPanelSource, /undo-request/, 'DrawioBoardPanel should not add a parallel app-level undo button')
assert.doesNotMatch(boardPanelSource, /redo-request/, 'DrawioBoardPanel should not add a parallel app-level redo button')
assert.match(boardPanelSource, /对话附图/, 'DrawioBoardPanel should use a concise conversation attachment label')
assert.doesNotMatch(boardPanelSource, /snapshotPending/, 'DrawioBoardPanel should treat conversation attachment as a one-shot action')
assert.doesNotMatch(boardPanelSource, /class=["'][^"']*board-btn[^"']*active|:class=.*active/, 'DrawioBoardPanel should not show the conversation attachment button as selected')
assert.doesNotMatch(rightPanelSource, /snapshot-pending/, 'RightPanelContainer should not pass selected state to DrawioBoardPanel')
assert.match(boardPanelSource, /board-snapshot-confirm/, 'DrawioBoardPanel should emit confirmed PNG snapshots')
assert.match(boardPanelSource, /action:\s*['"]export['"]|postDrawio\(['"]export['"]/, 'DrawioBoardPanel should request PNG export from draw.io')
assert.match(boardPanelSource, /导出图片/, 'DrawioBoardPanel should expose a manual image export action')
assert.match(boardPanelSource, /downloadBoardImage/, 'DrawioBoardPanel should download exported board images')
assert.match(boardPanelSource, /\.png/, 'DrawioBoardPanel should support PNG image downloads')
assert.match(boardPanelSource, /\.drawio/, 'DrawioBoardPanel should support .drawio downloads')
assert.doesNotMatch(boardPanelSource, /board-btn primary/, 'DrawioBoardPanel toolbar buttons should use a consistent visual style')

const mainViewSource = readFileSync(resolve('frontend/src/views/ReactAnalysisView.vue'), 'utf8')
const refactoredViewSource = readFileSync(resolve('frontend/src/views/ReactAnalysisViewRefactored.vue'), 'utf8')
assert.match(mainViewSource, /board-snapshot-confirm/, 'ReactAnalysisView should receive confirmed board snapshots')
assert.match(refactoredViewSource, /board-snapshot-confirm/, 'ReactAnalysisViewRefactored should receive confirmed board snapshots')
assert.doesNotMatch(mainLayoutSource, /board-undo-request/, 'MainLayout should not forward a duplicate app-level undo request')
assert.doesNotMatch(mainLayoutSource, /board-redo-request/, 'MainLayout should not forward a duplicate app-level redo request')
assert.doesNotMatch(rightPanelSource, /undo-request/, 'RightPanelContainer should not receive duplicate undo requests from DrawioBoardPanel')
assert.doesNotMatch(rightPanelSource, /redo-request/, 'RightPanelContainer should not receive duplicate redo requests from DrawioBoardPanel')
assert.doesNotMatch(mainViewSource, /undoDrawioBoard/, 'ReactAnalysisView should rely on draw.io built-in undo controls')
assert.doesNotMatch(refactoredViewSource, /undoDrawioBoard/, 'ReactAnalysisViewRefactored should rely on draw.io built-in undo controls')
assert.doesNotMatch(mainViewSource, /redoDrawioBoard/, 'ReactAnalysisView should rely on draw.io built-in redo controls')
assert.doesNotMatch(refactoredViewSource, /redoDrawioBoard/, 'ReactAnalysisViewRefactored should rely on draw.io built-in redo controls')
assert.match(rightPanelSource, /version-restore/, 'RightPanelContainer should receive draw.io version restore events')
assert.match(mainLayoutSource, /board-version-restore/, 'MainLayout should forward draw.io version restore events')
assert.match(mainViewSource, /restoreDrawioBoardVersion/, 'ReactAnalysisView should restore selected draw.io version files')
assert.match(refactoredViewSource, /restoreDrawioBoardVersion/, 'ReactAnalysisViewRefactored should restore selected draw.io version files')

assert.match(inputBoxSource, /pendingSnapshotAttachment/, 'InputBox should display pending draw.io board snapshots as attachments')
assert.match(inputBoxSource, /visibleAttachments/, 'InputBox should merge normal uploads with pending board snapshots for preview')
assert.match(inputBoxSource, /boardSelectionContextAttachment/, 'InputBox should show selected draw.io cells as a readonly context attachment')
assert.match(inputBoxSource, /drawio_board_selection/, 'InputBox should identify draw.io selection context attachments')
assert.match(inputBoxSource, /当前选中/, 'InputBox should label the current draw.io selection context clearly')
assert.match(inputBoxSource, /clearDrawioBoardSnapshotAttachment|setDrawioBoardSnapshotAttachment\(null/, 'InputBox should allow removing pending board snapshots')
