channels:
  send_max_retries: 3
  send_progress: true
  send_tool_hints: false
dingtalk:
  allow_from:
  - '*'
  app_key: ''
  app_secret: ''
  enabled: false
  streaming: false
qq:
  allow_from:
  - '*'
  app_id: ''
  enabled: false
  secret: ''
  streaming: false
wecom:
  agent_id: ''
  allow_from:
  - '*'
  corp_id: ''
  enabled: false
  secret: ''
  streaming: false
weixin:
  accounts:
  - allow_from:
    - '*'
    auto_start: true
    base_url: https://ilinkai.weixin.qq.com
    enabled: true
    id: auto_mn89uu4t
    name: 65a14590ea81@im.bot
    token: 65a14590ea81@im.bot:060000c26b682d87356a1e432ad68552efadab
  - allow_from:
    - '*'
    auto_start: true
    base_url: https://ilinkai.weixin.qq.com
    enabled: true
    id: auto_mn8k8rry
    name: 597a70dd5641@im.bot
    token: 597a70dd5641@im.bot:060000f1a03fd22a3051c3f70631cc35d5a899
  - allow_from:
    - '*'
    auto_start: true
    base_url: https://ilinkai.weixin.qq.com
    enabled: true
    id: auto_mn8ka95x
    name: aab9025fc8b4@im.bot
    token: aab9025fc8b4@im.bot:0600008bf30ffc32479bd65bb7f90acb3b60a4
  - allow_from:
    - '*'
    auto_start: true
    base_url: https://ilinkai.weixin.qq.com
    enabled: true
    id: auto_mn8nnwzs
    name: e20f11cc0912@im.bot
    token: e20f11cc0912@im.bot:0600001a6a73eb32e9685c39b842f1c9031a01
  enabled: true
