"""Resolve Jiangsu ops-platform RF form field dictionaries for audit.

The dictionaries under ``projects/jiangsu-ops/ops_audit/form_fields`` are
generated by ``projects/jiangsu-ops/ops_audit/extract_form_fields.py`` from the
platform front-end Vue form components.  Each platform form is stored in the
generic ``rFCommon`` matrix (``stringN``/``bool_N``/``timeN``/``remarkN``); this
module maps ``(ruleItemTag, orderType, pollutantType)`` to the component
dictionary so the generic columns can be translated into named business fields.

Component resolution mirrors the platform front-end (``CheckBase.vue`` et al):

    names = tag.split('_')
    if pollutantType != 'ALL' and tag not in COMMON_TAGS:
        names.append(pollutantType)
    component = '_'.join(names).replace('.', '')
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

from app.utils.path_config import PROJECT_ROOT

FORM_FIELDS_DIR = PROJECT_ROOT / "projects" / "jiangsu-ops" / "ops_audit" / "form_fields"

# Tags whose component ignores the pollutant suffix (platform front-end parity).
COMMON_TAG_NO_POLLUTANT = {
    "RF_HY_GasTightnessCheck",
    "RF_Q_GaseousMultipoint",
    "RF_Q_GaseousPrecision",
    "RF_W_PmCheck",
}

ORDER_TYPE_CATEGORY = {
    "Check": "check",
    "SECCheck": "check",
    "QC": "qcqa",
    "QA": "qcqa",
    "Calibration": "calibrating",
    "DataEntry": "dataentry",
}

BOOKKEEPING_COLUMNS = {
    "detailid", "iscancel", "workingordercode", "stationid", "deviceid", "ruleitemtag",
    "pollutanttype", "operationunitid", "checkdate", "prepareuserid", "preparenename",
    "prepareusername", "preparetime", "reviewuserid", "reviewusername", "reviewtime",
    "audituserid", "auditusername", "audittime", "createuserid", "createname", "createtime",
    "updateuserid", "updateusername", "updatetime", "id", "stringjson", "booljson",
    "remarkjson",
}

MISSING = object()


def component_name(rule_item_tag: str, pollutant_type: str | None) -> str:
    tag = str(rule_item_tag or "").strip()
    pollutant = str(pollutant_type or "").strip()
    names = tag.split("_")
    if pollutant and pollutant != "ALL" and tag not in COMMON_TAG_NO_POLLUTANT:
        names.append(pollutant)
    return "_".join(names).replace(".", "")


@lru_cache(maxsize=256)
def _load_json(path: str) -> dict[str, Any]:
    try:
        return json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}


def _candidate_paths(component: str, order_type: str | None) -> list[Path]:
    paths: list[Path] = []
    category = ORDER_TYPE_CATEGORY.get(str(order_type or ""))
    if category:
        paths.append(FORM_FIELDS_DIR / category / f"{component}.json")
    paths.extend(sorted(FORM_FIELDS_DIR.glob(f"*/{component}.json")))
    seen: set[Path] = set()
    unique: list[Path] = []
    for path in paths:
        if path not in seen:
            seen.add(path)
            unique.append(path)
    return unique


def load_form(
    rule_item_tag: str,
    *,
    order_type: str | None = None,
    pollutant_type: str | None = None,
) -> dict[str, Any] | None:
    """Return the form dictionary for one platform rule item, or ``None``."""
    component = component_name(rule_item_tag, pollutant_type)
    for path in _candidate_paths(component, order_type):
        if path.is_file():
            data = _load_json(str(path))
            if data:
                return data
    # Fall back to the bare tag (for platforms that do not append pollutant).
    if component != rule_item_tag:
        for path in _candidate_paths(str(rule_item_tag), order_type):
            if path.is_file():
                data = _load_json(str(path))
                if data:
                    return data
    return None


def translate_rfcommon(form: dict[str, Any] | None, rfcommon: dict[str, Any]) -> dict[str, Any]:
    """Translate a raw ``rFCommon`` dict into labelled fields and rows."""
    source = rfcommon or {}
    fields: list[dict[str, Any]] = []
    rows: list[dict[str, Any]] = []
    if form:
        for field in form.get("fields", []):
            column = field.get("column")
            if not column:
                continue
            fields.append(
                {
                    "column": column,
                    "label": field.get("label") or column,
                    "type": field.get("type") or "string",
                    "value": source.get(column),
                }
            )
        for row in form.get("rows", []):
            rows.append(
                {
                    "label": row.get("label"),
                    "status_column": row.get("status_column"),
                    "actual_column": row.get("actual_column"),
                    "remark_column": row.get("remark_column"),
                    "reference_limit": row.get("reference_limit") or "",
                    "status_value": source.get(row.get("status_column")) if row.get("status_column") else None,
                    "actual_value": source.get(row.get("actual_column")) if row.get("actual_column") else None,
                    "remark_value": source.get(row.get("remark_column")) if row.get("remark_column") else None,
                }
            )
    return {
        "component": (form or {}).get("component") or "",
        "matched": bool(form),
        "fields": fields,
        "rows": rows,
    }


def device_identity(rfcommon: dict[str, Any]) -> dict[str, Any]:
    source = rfcommon or {}
    return {
        "device_brand": source.get("deviceBrand"),
        "device_model": source.get("deviceModel"),
        "device_code": source.get("deviceCode"),
    }
