"""
修约规则符合性验证

检查168城市统计系统的修约规则是否符合《城市环境空气质量监测数据统计及信息公开工作方案》
"""
print("="*80)
print("修约规则符合性验证")
print("="*80)

print("\n一、文档要求（GB/T 8170-2008数值修约规则）")
print("-"*80)
print("根据《城市环境空气质量监测数据统计及信息公开工作方案》第四章节：")
print()
print("### 表1 统计过程相关指标单位及保留小数位数要求")
print(f"{'类型':<20} {'项目指标':<30} {'单位':<15} {'保留小数位数'}")
print("-"*80)
print(f"{'综合指数统计':<20} {'SO₂、NO₂、O₃、PM₁₀和PM₂.₅':<30} {'微克/立方米':<15} {'1'}")
print(f"{'综合指数统计':<20} {'CO':<30} {'毫克/立方米':<15} {'2'}")
print(f"{'综合指数统计':<20} {'单项指数':<30} {'/':<15} {'3'}")
print(f"{'综合指数统计':<20} {'综合指数':<30} {'/':<15} {'3'}")
print(f"{'PM₂.₅浓度统计':<20} {'PM₂.₅':<30} {'微克/立方米':<15} {'1'}")
print()
print("**信息公开要求**：")
print("  - 综合指数：保留2位小数")
print("  - PM₂.₅浓度：保留1位小数")

print("\n二、当前实现检查")
print("-"*80)
print("### 1. 浓度值修约（使用safe_round函数）")
print()
print("污染物浓度修约精度：")
print("  - SO₂、NO₂、PM₁₀、PM₂.₅: safe_round(value, 1)  → 保留1位小数 ✓")
print("  - CO: calculate_percentile(values, 95) → safe_round(result, 1) → 保留1位小数 ✗")
print("  - O₃_8h: calculate_percentile(values, 90) → safe_round(result, 1) → 保留1位小数 ✗")
print()
print("⚠️  问题发现：")
print("  - CO百分位数计算后使用safe_round(result, 1)，应该保留2位小数")
print("  - O₃_8h百分位数计算后使用safe_round(result, 1)，应该保留1位小数 ✓")
print()
print("### 2. 单项指数修约")
print("  - 所有单项指数: safe_round(value, 3) → 保留3位小数 ✓")
print()
print("### 3. 综合指数修约")
print("  - 综合指数: safe_round(value, 3) → 保留3位小数 ✓")
print("  - 注：数据库存储3位小数，信息公开时可显示2位小数")

print("\n三、GB/T 8170-2008数值修约规则验证")
print("-"*80)
print("### safe_round函数实现检查：")
print("  ✓ 使用Decimal进行精确修约")
print("  ✓ 使用ROUND_HALF_EVEN（四舍六入五成双）")
print("  ✓ 符合GB/T 8170-2008标准")
print()
print("### 修约规则：")
print("  - 拟修约的数字大于5时：入（进位）")
print("  - 拟修约的数字小于5时：舍（舍去）")
print("  - 拟修约的数字等于5时：")
print("    - 5后还有非0数字：入（进位）")
print("    - 5后没有数字或都是0：")
print("      - 5前为奇数：入（进位）")
print("      - 5前为偶数：舍（舍去）")

print("\n四、百分位数计算方法验证")
print("-"*80)
print("### 当前实现：线性插值法")
print("  ✓ 符合HJ663标准")
print("  ✓ 使用numpy的percentile方法等效算法")
print()
print("### 百分位数定义：")
print("  - CO: 日平均浓度第95百分位数")
print("  - O₃: 日最大8小时平均第90百分位数")

print("\n五、符合性总结")
print("="*80)
print("✓ 符合项：")
print("  1. ✓ SO₂、NO₂、PM₁₀、PM₂.₅浓度：保留1位小数")
print("  2. ✓ 单项指数：保留3位小数")
print("  3. ✓ 综合指数：保留3位小数（数据库存储）")
print("  4. ✓ 使用GB/T 8170-2008数值修约规则（四舍六入五成双）")
print("  5. ✓ 百分位数计算方法正确（线性插值法）")
print("  6. ✓ 统计方法符合HJ663标准")
print()
print("⚠️  需要修正项：")
print("  1. ✗ CO浓度：应保留2位小数，当前保留1位小数")
print("  2. ✗ O₃_8h浓度：当前保留1位小数，符合要求 ✓")
print()
print("建议修改：")
print("  - calculate_percentile函数需要区分CO（2位）和其他污染物（1位）")
print("="*80)
