# RF multipoint calibration hard checks.

linearity:
  slope_fields:
    - XL
    - SLOPE
    - SLOPEVALUE
  correlation_fields:
    - XGXS
    - CORRELATION
    - CORRELATIONCOEFFICIENT
  slope:
    min: 0.95
    max: 1.05
  correlation:
    min: 0.999
    operator: ">"
  intercept_fields:
    - JU
  intercept:
    ratio: 0.01
    tolerance: 0.0
  tolerance: 0.0005

tables:
  RF_HY_O3VALUEPASS:
    pollutant: O3
    history_tolerance: 1
    range_fields:
      - ISOK
  RF_Q_GASEOUSMULTIPOINT_CO:
    pollutant: CO
    history_tolerance: 1
    range_fields:
      - PPB
      - RANGE
      - RANG
      - MEASURERANGE
      - FULLSCALE
      - RANGEVALUE
      - DEVICE_RANGE
      - DEVICERANGE
      - CALIBRATIONRANGE
  RF_Q_GASEOUSMULTIPOINT_NO2:
    pollutant: NO2
    history_tolerance: 1
    range_fields:
      - PPB
      - RANGE
      - RANG
      - MEASURERANGE
      - FULLSCALE
      - RANGEVALUE
      - DEVICE_RANGE
      - DEVICERANGE
      - CALIBRATIONRANGE
  RF_Q_GASEOUSMULTIPOINT_O3:
    pollutant: O3
    history_tolerance: 1
    range_fields:
      - PPB
      - RANGE
      - RANG
      - MEASURERANGE
      - FULLSCALE
      - RANGEVALUE
      - DEVICE_RANGE
      - DEVICERANGE
      - CALIBRATIONRANGE
  RF_Q_GASEOUSMULTIPOINT_SO2:
    pollutant: SO2
    history_tolerance: 1
    range_fields:
      - PPB
      - RANGE
      - RANG
      - MEASURERANGE
      - FULLSCALE
      - RANGEVALUE
      - DEVICE_RANGE
      - DEVICERANGE
      - CALIBRATIONRANGE
